[build]
builder = "NIXPACKS"
buildCommand = "cd app && npm ci && npm run build:web"

[deploy]
startCommand = "cd app && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 3000