[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm ci && cd ../app && npm ci && npm run build:web && cp -r dist ../server/public"

[deploy]
startCommand = "cd server && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3