[build]
builder = "NIXPACKS"
buildCommand = "if [ \"$RAILWAY_SERVICE_NAME\" = \"courtesy-frontend\" ]; then cd app && npm ci && npm run build:web; else cd server && npm ci; fi"

[deploy]
startCommand = "if [ \"$RAILWAY_SERVICE_NAME\" = \"courtesy-frontend\" ]; then cd app && node server.js; else cd server && node server.js; fi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3